//go:build linux

package handoffhelper

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"syscall"
	"time"
)

const (
	participantProtocolSchema = 1
	// ParticipantObservePath is the sole owner-control endpoint used by the
	// helper to challenge a capability-routed participant.
	ParticipantObservePath = "/v1/namespace-handoff/participant/observe"
	maxParticipantRequest  = 8 << 10
	maxParticipantResponse = 32 << 10
)

var (
	participantNoncePattern  = regexp.MustCompile(`^[0-9a-f]{64}$`)
	participantSHA256Pattern = regexp.MustCompile(`^[0-9a-f]{64}$`)
	participantCommitPattern = regexp.MustCompile(`^[0-9a-f]{40}$`)
)

// ParticipantChallenge is closed-world input to the owner-only control
// endpoint exposed by a helper-started source/target Manager.
type ParticipantChallenge struct {
	SchemaVersion int             `json:"schema_version"`
	TransactionID string          `json:"transaction_id"`
	Revision      uint64          `json:"revision"`
	BindingSHA256 string          `json:"binding_sha256"`
	Role          ParticipantRole `json:"role"`
	Nonce         string          `json:"nonce"`
}

// ParticipantObservation is generated by the participant from its consumed
// StartupSnapshot, running executable, control socket, core readiness and
// gateway controller. ProofSHA256 covers every preceding field in this exact
// struct; the helper recomputes it before trusting any value.
type ParticipantObservation struct {
	SchemaVersion       int             `json:"schema_version"`
	TransactionID       string          `json:"transaction_id"`
	StartupRevision     uint64          `json:"startup_revision"`
	BindingSHA256       string          `json:"binding_sha256"`
	Role                ParticipantRole `json:"role"`
	Nonce               string          `json:"nonce"`
	ManagerVersion      string          `json:"manager_version"`
	SourceCommit        string          `json:"source_commit"`
	ExecutableSHA256    string          `json:"executable_sha256"`
	PID                 int             `json:"pid"`
	SocketPath          string          `json:"socket_path"`
	CoreReady           bool            `json:"core_ready"`
	PublicListenerOwned bool            `json:"public_listener_owned"`
	ReadyToCommit       bool            `json:"ready_to_commit"`
	AutoUpdateCheckAt   time.Time       `json:"auto_update_check_at"`
	IssuedAt            time.Time       `json:"issued_at"`
	ProofSHA256         string          `json:"proof_sha256"`
}

type participantProofMaterial struct {
	SchemaVersion       int             `json:"schema_version"`
	TransactionID       string          `json:"transaction_id"`
	StartupRevision     uint64          `json:"startup_revision"`
	BindingSHA256       string          `json:"binding_sha256"`
	Role                ParticipantRole `json:"role"`
	Nonce               string          `json:"nonce"`
	ManagerVersion      string          `json:"manager_version"`
	SourceCommit        string          `json:"source_commit"`
	ExecutableSHA256    string          `json:"executable_sha256"`
	PID                 int             `json:"pid"`
	SocketPath          string          `json:"socket_path"`
	CoreReady           bool            `json:"core_ready"`
	PublicListenerOwned bool            `json:"public_listener_owned"`
	ReadyToCommit       bool            `json:"ready_to_commit"`
	AutoUpdateCheckAt   time.Time       `json:"auto_update_check_at"`
	IssuedAt            time.Time       `json:"issued_at"`
}

// ComputeParticipantProof is shared by the participant control handler and
// helper client. Encoding a fixed struct (rather than a map) makes the digest
// deterministic without accepting arbitrary JSON.
func ComputeParticipantProof(observation ParticipantObservation) (string, error) {
	material := participantProofMaterial{
		SchemaVersion: observation.SchemaVersion, TransactionID: observation.TransactionID,
		StartupRevision: observation.StartupRevision, BindingSHA256: observation.BindingSHA256,
		Role: observation.Role, Nonce: observation.Nonce, ManagerVersion: observation.ManagerVersion,
		SourceCommit: observation.SourceCommit, ExecutableSHA256: observation.ExecutableSHA256,
		PID: observation.PID, SocketPath: observation.SocketPath, CoreReady: observation.CoreReady,
		PublicListenerOwned: observation.PublicListenerOwned, ReadyToCommit: observation.ReadyToCommit,
		AutoUpdateCheckAt: observation.AutoUpdateCheckAt.UTC(), IssuedAt: observation.IssuedAt.UTC(),
	}
	encoded, err := json.Marshal(material)
	if err != nil {
		return "", err
	}
	digest := sha256.Sum256(encoded)
	return hex.EncodeToString(digest[:]), nil
}

type ParticipantObserver interface {
	Observe(context.Context, ParticipantRole, ParticipantChallenge) (ParticipantObservation, error)
}

type ParticipantControlBinding struct {
	SocketPath string
	TokenPath  string
	MainPID    int
}

type ParticipantControlResolver interface {
	ResolveParticipantControl(context.Context, ParticipantRole) (ParticipantControlBinding, error)
}

type ParticipantControlResolverFunc func(context.Context, ParticipantRole) (ParticipantControlBinding, error)

func (function ParticipantControlResolverFunc) ResolveParticipantControl(ctx context.Context, role ParticipantRole) (ParticipantControlBinding, error) {
	return function(ctx, role)
}

type UnixParticipantObserver struct {
	Resolver ParticipantControlResolver
	Timeout  time.Duration
}

func (observer UnixParticipantObserver) Observe(ctx context.Context, role ParticipantRole, challenge ParticipantChallenge) (ParticipantObservation, error) {
	if role != ParticipantSource && role != ParticipantTarget {
		return ParticipantObservation{}, errors.New("participant observation role is invalid")
	}
	if observer.Resolver == nil {
		return ParticipantObservation{}, errors.New("participant control resolver is unavailable")
	}
	if err := ValidateParticipantChallenge(challenge); err != nil || challenge.Role != role {
		return ParticipantObservation{}, errors.Join(errors.New("participant challenge differs from its requested role"), err)
	}
	binding, err := observer.Resolver.ResolveParticipantControl(ctx, role)
	if err != nil {
		return ParticipantObservation{}, err
	}
	if !canonicalAbsolute(binding.SocketPath) || !canonicalAbsolute(binding.TokenPath) || binding.MainPID <= 1 {
		return ParticipantObservation{}, errors.New("participant control binding is invalid")
	}
	token, err := readParticipantToken(binding.TokenPath)
	if err != nil {
		return ParticipantObservation{}, fmt.Errorf("read participant control token: %w", err)
	}
	body, err := json.Marshal(challenge)
	if err != nil {
		return ParticipantObservation{}, err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPost, "http://manager"+ParticipantObservePath, bytes.NewReader(body))
	if err != nil {
		return ParticipantObservation{}, err
	}
	request.Header.Set("Authorization", "Bearer "+token)
	request.Header.Set("Content-Type", "application/json")
	timeout := observer.Timeout
	if timeout <= 0 {
		timeout = 10 * time.Second
	}
	transport := &http.Transport{DialContext: func(ctx context.Context, _, _ string) (net.Conn, error) {
		return dialBoundParticipant(ctx, binding, timeout)
	}}
	client := &http.Client{Transport: transport, Timeout: timeout}
	response, err := client.Do(request)
	if err != nil {
		return ParticipantObservation{}, err
	}
	defer response.Body.Close()
	data, err := io.ReadAll(io.LimitReader(response.Body, maxParticipantResponse+1))
	if err != nil {
		return ParticipantObservation{}, err
	}
	if len(data) > maxParticipantResponse {
		return ParticipantObservation{}, errors.New("participant observation exceeds 32 KiB")
	}
	if response.StatusCode < 200 || response.StatusCode >= 300 {
		return ParticipantObservation{}, fmt.Errorf("participant control HTTP %d: %s", response.StatusCode, strings.TrimSpace(string(data)))
	}
	result, err := DecodeParticipantObservation(bytes.NewReader(data))
	if err != nil {
		return ParticipantObservation{}, err
	}
	if err := ValidateParticipantObservation(challenge, result); err != nil {
		return ParticipantObservation{}, err
	}
	return result, nil
}

// DecodeParticipantChallenge and DecodeParticipantObservation are the only
// control-handler codecs. They reject oversized, duplicate, unknown, missing,
// and trailing fields before returning a typed value.
func DecodeParticipantChallenge(reader io.Reader) (ParticipantChallenge, error) {
	var challenge ParticipantChallenge
	if err := decodeParticipantJSON(reader, maxParticipantRequest, participantChallengeFields, &challenge); err != nil {
		return ParticipantChallenge{}, fmt.Errorf("decode participant challenge: %w", err)
	}
	if err := ValidateParticipantChallenge(challenge); err != nil {
		return ParticipantChallenge{}, err
	}
	return challenge, nil
}

func DecodeParticipantObservation(reader io.Reader) (ParticipantObservation, error) {
	var observation ParticipantObservation
	if err := decodeParticipantJSON(reader, maxParticipantResponse, participantObservationFields, &observation); err != nil {
		return ParticipantObservation{}, fmt.Errorf("decode participant observation: %w", err)
	}
	return observation, nil
}

func EncodeParticipantObservation(observation ParticipantObservation) ([]byte, error) {
	if err := validateParticipantObservationShape(observation); err != nil {
		return nil, err
	}
	encoded, err := json.Marshal(observation)
	if err != nil {
		return nil, err
	}
	if len(encoded) > maxParticipantResponse {
		return nil, errors.New("participant observation exceeds 32 KiB")
	}
	return encoded, nil
}

func ValidateParticipantChallenge(challenge ParticipantChallenge) error {
	if challenge.SchemaVersion != participantProtocolSchema || !transactionPattern.MatchString(challenge.TransactionID) ||
		challenge.Revision == 0 || !participantSHA256Pattern.MatchString(challenge.BindingSHA256) ||
		(challenge.Role != ParticipantSource && challenge.Role != ParticipantTarget) || !participantNoncePattern.MatchString(challenge.Nonce) {
		return errors.New("participant challenge binding is invalid")
	}
	return nil
}

// ValidateParticipantObservation is shared by the provider and client. It
// checks the nonce-bound closed protocol; generation-specific facts remain a
// ProductionParticipant responsibility.
func ValidateParticipantObservation(challenge ParticipantChallenge, observation ParticipantObservation) error {
	if err := ValidateParticipantChallenge(challenge); err != nil {
		return err
	}
	if err := validateParticipantObservationShape(observation); err != nil {
		return err
	}
	if observation.TransactionID != challenge.TransactionID || observation.BindingSHA256 != challenge.BindingSHA256 ||
		observation.Role != challenge.Role || observation.Nonce != challenge.Nonce || observation.StartupRevision > challenge.Revision {
		return errors.New("participant observation differs from its challenge")
	}
	wantProof, err := ComputeParticipantProof(observation)
	if err != nil || wantProof != observation.ProofSHA256 {
		return errors.New("participant observation proof digest is invalid")
	}
	return nil
}

func validateParticipantObservationShape(observation ParticipantObservation) error {
	if observation.SchemaVersion != participantProtocolSchema || !transactionPattern.MatchString(observation.TransactionID) ||
		observation.StartupRevision == 0 || !participantSHA256Pattern.MatchString(observation.BindingSHA256) ||
		(observation.Role != ParticipantSource && observation.Role != ParticipantTarget) ||
		!participantNoncePattern.MatchString(observation.Nonce) || observation.ManagerVersion == "" ||
		!participantCommitPattern.MatchString(observation.SourceCommit) || !participantSHA256Pattern.MatchString(observation.ExecutableSHA256) ||
		observation.PID <= 1 || observation.SocketPath == "" || strings.ContainsRune(observation.SocketPath, '\x00') || observation.IssuedAt.IsZero() ||
		!participantSHA256Pattern.MatchString(observation.ProofSHA256) {
		return errors.New("participant observation shape is invalid")
	}
	return nil
}

func decodeParticipantJSON(reader io.Reader, limit int64, fields []string, destination any) error {
	if reader == nil {
		return errors.New("participant JSON body is unavailable")
	}
	data, err := io.ReadAll(io.LimitReader(reader, limit+1))
	if err != nil {
		return err
	}
	if len(data) == 0 || int64(len(data)) > limit {
		return errors.New("participant JSON body size is invalid")
	}
	if err := rejectParticipantDuplicateJSON(data); err != nil {
		return err
	}
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil || object == nil || len(object) != len(fields) {
		return errors.New("participant JSON fields do not match the closed schema")
	}
	for _, field := range fields {
		if _, ok := object[field]; !ok {
			return fmt.Errorf("participant JSON is missing field %q", field)
		}
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(destination); err != nil {
		return err
	}
	return ensureJSONEOF(decoder)
}

func rejectParticipantDuplicateJSON(data []byte) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	var walk func() error
	walk = func() error {
		token, err := decoder.Token()
		if err != nil {
			return err
		}
		delimiter, ok := token.(json.Delim)
		if !ok {
			return nil
		}
		switch delimiter {
		case '{':
			seen := map[string]struct{}{}
			for decoder.More() {
				keyToken, err := decoder.Token()
				if err != nil {
					return err
				}
				key, ok := keyToken.(string)
				if !ok {
					return errors.New("participant JSON key is not a string")
				}
				if _, exists := seen[key]; exists {
					return fmt.Errorf("participant JSON contains duplicate field %q", key)
				}
				seen[key] = struct{}{}
				if err := walk(); err != nil {
					return err
				}
			}
			_, err = decoder.Token()
			return err
		case '[':
			for decoder.More() {
				if err := walk(); err != nil {
					return err
				}
			}
			_, err = decoder.Token()
			return err
		default:
			return errors.New("participant JSON contains an unexpected delimiter")
		}
	}
	return walk()
}

func readParticipantToken(path string) (string, error) {
	parent, err := openParticipantDirectoryNoFollow(filepath.Dir(path))
	if err != nil {
		return "", err
	}
	defer parent.Close()
	fd, err := syscall.Openat(int(parent.Fd()), filepath.Base(path), syscall.O_RDONLY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC, 0)
	if err != nil {
		return "", err
	}
	file := os.NewFile(uintptr(fd), path)
	defer file.Close()
	var stat syscall.Stat_t
	if err := syscall.Fstat(fd, &stat); err != nil {
		return "", err
	}
	if stat.Mode&syscall.S_IFMT != syscall.S_IFREG || stat.Uid != uint32(os.Getuid()) || stat.Nlink != 1 || stat.Mode&0o777 != 0o600 || stat.Size <= 0 || stat.Size > 8192 {
		return "", errors.New("participant control token file identity is invalid")
	}
	data, err := io.ReadAll(io.LimitReader(file, 8193))
	if err != nil || len(data) > 8192 {
		return "", errors.Join(err, errors.New("participant control token file is oversized"))
	}
	var after syscall.Stat_t
	if err := syscall.Fstat(fd, &after); err != nil || after.Dev != stat.Dev || after.Ino != stat.Ino || after.Size != stat.Size {
		return "", errors.New("participant control token changed while reading")
	}
	token := strings.TrimSuffix(string(data), "\n")
	if token == "" || strings.ContainsAny(token, " \t\r\n\x00") {
		return "", errors.New("participant control token is invalid")
	}
	return token, nil
}

func dialBoundParticipant(ctx context.Context, binding ParticipantControlBinding, timeout time.Duration) (net.Conn, error) {
	directory, err := openParticipantDirectoryNoFollow(filepath.Dir(binding.SocketPath))
	if err != nil {
		return nil, err
	}
	defer directory.Close()
	procPath := filepath.Join("/proc/self/fd", strconv.Itoa(int(directory.Fd())), filepath.Base(binding.SocketPath))
	before, err := inspectParticipantSocket(procPath)
	if err != nil {
		return nil, err
	}
	raw, err := (&net.Dialer{Timeout: timeout}).DialContext(ctx, "unix", procPath)
	if err != nil {
		return nil, err
	}
	connection, ok := raw.(*net.UnixConn)
	if !ok {
		_ = raw.Close()
		return nil, errors.New("participant control connection is not Unix")
	}
	after, err := inspectParticipantSocket(procPath)
	if err != nil || after != before {
		_ = connection.Close()
		return nil, errors.New("participant control socket changed while connecting")
	}
	rawControl, err := connection.SyscallConn()
	if err != nil {
		_ = connection.Close()
		return nil, err
	}
	var credentials *syscall.Ucred
	var controlErr error
	if err := rawControl.Control(func(fd uintptr) {
		credentials, controlErr = syscall.GetsockoptUcred(int(fd), syscall.SOL_SOCKET, syscall.SO_PEERCRED)
	}); err != nil {
		_ = connection.Close()
		return nil, err
	}
	if controlErr != nil || credentials == nil || int(credentials.Pid) != binding.MainPID || credentials.Uid != uint32(os.Getuid()) {
		_ = connection.Close()
		return nil, errors.Join(controlErr, fmt.Errorf("participant control peer is not systemd MainPID %s", strconv.Itoa(binding.MainPID)))
	}
	return connection, nil
}

func openParticipantDirectoryNoFollow(path string) (*os.File, error) {
	if !canonicalAbsolute(path) {
		return nil, errors.New("participant control directory path is invalid")
	}
	current, err := syscall.Open(string(filepath.Separator), syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_CLOEXEC, 0)
	if err != nil {
		return nil, err
	}
	for _, component := range strings.Split(strings.TrimPrefix(path, string(filepath.Separator)), string(filepath.Separator)) {
		if component == "" {
			continue
		}
		next, openErr := syscall.Openat(current, component, syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC, 0)
		_ = syscall.Close(current)
		if openErr != nil {
			return nil, openErr
		}
		current = next
	}
	var stat syscall.Stat_t
	if err := syscall.Fstat(current, &stat); err != nil {
		_ = syscall.Close(current)
		return nil, err
	}
	if stat.Mode&syscall.S_IFMT != syscall.S_IFDIR || stat.Uid != uint32(os.Getuid()) || stat.Mode&0o777 != 0o700 {
		_ = syscall.Close(current)
		return nil, errors.New("participant control directory is not owner-only")
	}
	return os.NewFile(uintptr(current), path), nil
}

type participantSocketIdentity struct {
	device uint64
	inode  uint64
	uid    uint32
	mode   uint32
}

func inspectParticipantSocket(path string) (participantSocketIdentity, error) {
	if !canonicalAbsolute(path) {
		return participantSocketIdentity{}, errors.New("participant control socket path is invalid")
	}
	info, err := os.Lstat(path)
	if err != nil {
		return participantSocketIdentity{}, err
	}
	stat, ok := info.Sys().(*syscall.Stat_t)
	if !ok || stat.Mode&syscall.S_IFMT != syscall.S_IFSOCK || stat.Uid != uint32(os.Getuid()) || stat.Mode&0o022 != 0 {
		return participantSocketIdentity{}, errors.New("participant control socket identity is invalid")
	}
	return participantSocketIdentity{device: uint64(stat.Dev), inode: stat.Ino, uid: stat.Uid, mode: stat.Mode}, nil
}

func ensureJSONEOF(decoder *json.Decoder) error {
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err == nil {
			return errors.New("participant observation contains extra JSON")
		}
		return fmt.Errorf("decode participant observation trailer: %w", err)
	}
	return nil
}

func newParticipantChallenge(operation Operation, role ParticipantRole) (ParticipantChallenge, error) {
	var nonce [32]byte
	if _, err := rand.Read(nonce[:]); err != nil {
		return ParticipantChallenge{}, err
	}
	return ParticipantChallenge{
		SchemaVersion: participantProtocolSchema, TransactionID: operation.TransactionID,
		Revision: operation.Revision, BindingSHA256: operation.BindingSHA256,
		Role: role, Nonce: hex.EncodeToString(nonce[:]),
	}, nil
}

var participantChallengeFields = []string{
	"schema_version", "transaction_id", "revision", "binding_sha256", "role", "nonce",
}

var participantObservationFields = []string{
	"schema_version", "transaction_id", "startup_revision", "binding_sha256", "role", "nonce",
	"manager_version", "source_commit", "executable_sha256", "pid", "socket_path", "core_ready",
	"public_listener_owned", "ready_to_commit", "auto_update_check_at", "issued_at", "proof_sha256",
}
