/* Source-derived compositions: Beautiful UI SidebarNav, RecordsTable,
 * ContextCards, TaskRows and StatusPill. See NOTICE / LICENSE. */
import { createContext, useContext, useId, useState, type ReactNode } from "react";
import { Button } from "./Controls";
import { Glyph } from "./Glyph";
import { Overlay } from "./Overlay";
export type Tone = "neutral" | "info" | "success" | "warning" | "danger";
export type BrandIdentity = { productName: string; logoUrl?: string | null };
const NavigationClose = createContext<(() => void) | undefined>(undefined);
export function BrandMark({ productName, logoUrl, compact = false }: BrandIdentity & { compact?: boolean }) {
  const [failedUrl, setFailedUrl] = useState<string | null>(null);
  return <div className={`bui-brand${compact ? " bui-brand--compact" : ""}`}>{logoUrl && logoUrl !== failedUrl && <img src={logoUrl} alt="" onError={() => setFailedUrl(logoUrl)} />}<span>{productName}</span></div>;
}
export interface AppFrameProps { brand: BrandIdentity; navigation: ReactNode; account: ReactNode; utilities?: ReactNode; children: ReactNode; navigationLabel: string; openNavigationLabel: string; closeNavigationLabel: string; skipLabel: string; mobileTitle?: ReactNode; navigationOpen: boolean; onNavigationOpenChange: (open: boolean) => void }
export function AppFrame({ brand, navigation, account, utilities, children, navigationLabel, openNavigationLabel, closeNavigationLabel, skipLabel, mobileTitle, navigationOpen, onNavigationOpenChange }: AppFrameProps) {
  const contents = <><div className="bui-sidebar-scroll">{navigation}</div><footer className="bui-sidebar-footer">{account}{utilities && <div className="bui-actions">{utilities}</div>}</footer></>;
  return <NavigationClose.Provider value={() => onNavigationOpenChange(false)}><div className="bui-app-frame"><a className="bui-skip" href="#bui-main">{skipLabel}</a><aside className="bui-sidebar" aria-label={navigationLabel}><div className="bui-sidebar-brand"><BrandMark {...brand} /></div>{contents}</aside><header className="bui-mobile-bar"><Button aria-label={openNavigationLabel} aria-expanded={navigationOpen} variant="quiet" icon={<Glyph name="menu" />} onClick={() => onNavigationOpenChange(true)} /><BrandMark {...brand} compact /><span>{mobileTitle}</span></header><main className="bui-main" id="bui-main" tabIndex={-1}>{children}</main><Overlay open={navigationOpen} onClose={() => onNavigationOpenChange(false)} title={<BrandMark {...brand} />} label={navigationLabel} closeLabel={closeNavigationLabel} placement="left" className="bui-navigation-overlay">{contents}</Overlay></div></NavigationClose.Provider>;
}
export interface NavigationItem { key: string; label: ReactNode; description?: ReactNode; icon?: ReactNode; trailing?: ReactNode; disabled?: boolean }
export interface NavigationGroup { key: string; label: ReactNode; action?: ReactNode; items: NavigationItem[] }
export interface NavigationProps { label: string; groups: NavigationGroup[]; activeKey?: string; onSelect: (key: string) => void }
export function WorkspaceNav({ label, groups, activeKey, onSelect }: NavigationProps) {
  const close = useContext(NavigationClose);
  return <nav className="bui-navigation" aria-label={label}>{groups.map((group) => <section className="bui-nav-group" key={group.key}><header><span className="bui-eyebrow">{group.label}</span>{group.action}</header><ul>{group.items.map((item) => <li key={item.key} className={activeKey === item.key ? "bui-nav-row bui-nav-row--active" : "bui-nav-row"}><button type="button" aria-current={activeKey === item.key ? "page" : undefined} disabled={item.disabled} onClick={() => { onSelect(item.key); close?.(); }}><span className="bui-nav-icon">{item.icon}</span><span className="bui-nav-copy"><span>{item.label}</span>{item.description && <small>{item.description}</small>}</span></button>{item.trailing && <span className="bui-nav-trailing">{item.trailing}</span>}</li>)}</ul></section>)}</nav>;
}
export function SectionIndex({ label, groups, activeKey, onSelect }: NavigationProps) {
  return <nav className="bui-section-index" aria-label={label}>{groups.map((group) => <div key={group.key}>{group.label && <span className="bui-eyebrow">{group.label}</span>}<div className="bui-actions">{group.items.map((item) => <Button variant={item.key === activeKey ? "secondary" : "quiet"} key={item.key} size="sm" aria-current={item.key === activeKey ? "page" : undefined} onClick={() => onSelect(item.key)} disabled={item.disabled} icon={item.icon}>{item.label}{item.trailing}</Button>)}</div></div>)}</nav>;
}
export interface PageHeaderProps { eyebrow?: ReactNode; title: ReactNode; description?: ReactNode; meta?: ReactNode; actions?: ReactNode }
export function PageHeader({ eyebrow, title, description, meta, actions }: PageHeaderProps) {
  return <header className="bui-page-header"><div>{eyebrow && <div className="bui-eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description && <div className="bui-muted">{description}</div>}{meta && <div className="bui-page-meta">{meta}</div>}</div>{actions && <div className="bui-actions">{actions}</div>}</header>;
}
export function PageLayout({ header, navigation, children }: { header: ReactNode; navigation?: ReactNode; children: ReactNode }) {
  return <div className="bui-page"><div className="bui-page-top">{header}{navigation}</div><div className="bui-page-scroll"><div className="bui-page-content">{children}</div></div></div>;
}
export function Section({ id, title, description, actions, children, tone = "plain" }: { id?: string; title?: ReactNode; description?: ReactNode; actions?: ReactNode; children: ReactNode; tone?: "plain" | "inset" | "danger" }) {
  const heading = useId();
  return <section id={id} className={`bui-section bui-section--${tone}`} aria-labelledby={title ? heading : undefined}>{(title || description || actions) && <header><div>{title && <h2 id={heading}>{title}</h2>}{description && <div className="bui-muted">{description}</div>}</div>{actions && <div className="bui-actions">{actions}</div>}</header>}<div className="bui-section-content">{children}</div></section>;
}
export function FormGrid({ children, columns = 2 }: { children: ReactNode; columns?: 1 | 2 }) { return <div className={`bui-form-grid bui-form-grid--${columns}`}>{children}</div>; }
export function FormFooter({ note, children }: { note?: ReactNode; children: ReactNode }) { return <footer className="bui-form-footer">{note && <div className="bui-muted">{note}</div>}<div className="bui-actions">{children}</div></footer>; }
export function StatusMark({ tone = "neutral", children, subtle = false }: { tone?: Tone; children: ReactNode; subtle?: boolean }) { return <span className={`bui-status bui-tone-${tone}${subtle ? " bui-status--subtle" : ""}`}><span className="bui-status-dot" aria-hidden="true" />{children}</span>; }
export function Notice({ tone = "info", title, children, action }: { tone?: Tone; title: ReactNode; children?: ReactNode; action?: ReactNode }) { return <div className={`bui-notice bui-tone-${tone}`} role={tone === "danger" ? "alert" : "status"}><Glyph name={tone === "warning" || tone === "danger" ? "warning" : tone === "success" ? "check" : "file"} size={16} /><div className="bui-notice-copy"><strong>{title}</strong>{children && <div>{children}</div>}</div>{action}</div>; }
export function EmptyState({ eyebrow, title, description, action, compact = false }: { eyebrow?: ReactNode; title: ReactNode; description?: ReactNode; action?: ReactNode; compact?: boolean }) { return <section className={`bui-empty${compact ? " bui-empty--compact" : ""}`}>{eyebrow && <span className="bui-eyebrow">{eyebrow}</span>}<h2>{title}</h2>{description && <div >{description}</div>}{action && <div className="bui-actions">{action}</div>}</section>; }
export function LoadingState({ label, detail }: { label: ReactNode; detail?: ReactNode }) { return <div className="bui-loading" role="status"><span className="bui-spinner" aria-hidden="true" /><div><strong>{label}</strong>{detail && <div className="bui-muted">{detail}</div>}</div></div>; }
export interface DataRegionProps { state: "loading" | "error" | "empty" | "ready"; loadingLabel: ReactNode; error?: ReactNode; empty?: ReactNode; retry?: ReactNode; refreshing?: boolean; refreshingLabel?: ReactNode; children?: ReactNode }
export function DataRegion({ state, loadingLabel, error, empty, retry, refreshing = false, refreshingLabel, children }: DataRegionProps) {
  if (state === "loading") return <LoadingState label={loadingLabel} />;
  if (state === "error") return <Notice tone="danger" title={error} action={retry} />;
  return <div className="bui-data-region" aria-busy={refreshing}>{error && <Notice tone="danger" title={error} action={retry} />}{refreshing && <LoadingState label={refreshingLabel ?? loadingLabel} />}<div inert={refreshing || undefined}>{state === "empty" ? empty : children}</div></div>;
}
export function ResourceList({ children, label }: { children: ReactNode; label?: string }) { return <ul className="bui-resource-list" aria-label={label}>{children}</ul>; }
export interface ResourceRowProps { leading?: ReactNode; title: ReactNode; description?: ReactNode; meta?: ReactNode; status?: ReactNode; actions?: ReactNode; children?: ReactNode; selected?: boolean; onSelect?: () => void; selectLabel?: string }
export function ResourceRow({ leading, title, description, meta, status, actions, children, selected = false, onSelect, selectLabel }: ResourceRowProps) { return <li className={`bui-resource-row${selected ? " bui-resource-row--selected" : ""}`}><div className="bui-resource-summary">{leading}<div className="bui-resource-copy"><div className="bui-inline">{onSelect ? <Button variant="quiet" size="sm" aria-label={selectLabel} aria-pressed={selected} onClick={onSelect}>{title}<Glyph name="chevron" size={14} /></Button> : <strong>{title}</strong>}{status}</div>{description && <div className="bui-muted">{description}</div>}{meta && <div className="bui-resource-meta">{meta}</div>}</div>{actions && <div className="bui-actions">{actions}</div>}</div>{children && <div className="bui-resource-detail">{children}</div>}</li>; }
export interface FactItem { key: string; label: ReactNode; value: ReactNode; hint?: ReactNode; tone?: Tone }
export function FactGrid({ items, columns = 3 }: { items: FactItem[]; columns?: 2 | 3 | 4 }) { return <dl className={`bui-facts bui-facts--${columns}`}>{items.map((item) => <div key={item.key}><dt>{item.label}</dt><dd className={item.tone ? `bui-tone-${item.tone}` : undefined}>{item.value}</dd>{item.hint && <dd className="bui-muted">{item.hint}</dd>}</div>)}</dl>; }
export function SplitDetail({ list, detail, detailOpen, onBack, backLabel }: { list: ReactNode; detail?: ReactNode; detailOpen: boolean; onBack?: () => void; backLabel: string }) { return <div className={`bui-split${detailOpen ? " bui-split--open" : ""}`}><div className="bui-split-list">{list}</div><div className="bui-split-detail">{detailOpen && onBack && <Button variant="quiet" className="bui-split-back" icon={<Glyph name="back" />} onClick={onBack}>{backLabel}</Button>}{detail}</div></div>; }
export interface AuthPageProps { brand: BrandIdentity; title: ReactNode; description?: ReactNode; form: ReactNode; utilities?: ReactNode; footnote?: ReactNode }
export function AuthPage({ brand, title, description, form, utilities, footnote }: AuthPageProps) { return <main className="bui-public"><header className="bui-public-header"><BrandMark {...brand} /><div className="bui-actions">{utilities}</div></header><section className="bui-auth-panel"><h1>{title}</h1>{description && <div className="bui-muted">{description}</div>}<div className="bui-auth-form">{form}</div>{footnote && <footer className="bui-muted">{footnote}</footer>}</section></main>; }
export interface RecoveryPageProps { brand: BrandIdentity; title: ReactNode; description?: ReactNode; status?: ReactNode; actions?: ReactNode; utilities?: ReactNode; detail?: ReactNode }
export function RecoveryPage({ brand, title, description, status, actions, utilities, detail }: RecoveryPageProps) { return <main className="bui-public"><header className="bui-public-header"><BrandMark {...brand} /><div className="bui-actions">{utilities}</div></header><section className="bui-recovery-panel"><h1>{title}</h1>{description && <div className="bui-muted">{description}</div>}{status}{detail && <div className="bui-recovery-detail">{detail}</div>}{actions && <div className="bui-actions">{actions}</div>}</section></main>; }
export interface OverlayPanelProps { open: boolean; onClose: () => void; title: ReactNode; description?: ReactNode; children: ReactNode; footer?: ReactNode; size?: "standard" | "wide"; closeLabel: string }
export function OverlayPanel({ size, ...props }: OverlayPanelProps) { return <Overlay {...props} placement="right" wide={size === "wide"} />; }
