/* Beautiful UI ChatComposer / PromptBar / ToolChips / TaskRows / ApprovalCard
 * / AgentScreen composition adaptations. No simulated work or message state.
 * Copyright (c) 2026 Shane Levine; see LICENSE and NOTICE. */
import { useId, useState, type ReactNode, type Ref, type UIEventHandler } from "react";
import { Button, Tooltip } from "./Controls";
import { Glyph } from "./Glyph";
export interface ConversationLayoutProps { header: ReactNode; children: ReactNode; composer: ReactNode; floatingActions?: ReactNode; companion?: ReactNode; notice?: ReactNode; threadRef?: Ref<HTMLDivElement>; onThreadScroll?: UIEventHandler<HTMLDivElement>; threadLabel: string }
export function ConversationLayout({ header, children, composer, floatingActions, companion, notice, threadRef, onThreadScroll, threadLabel }: ConversationLayoutProps) {
  return <div className="bui-conversation"><header className="bui-conversation-header">{header}</header>{notice && <div className="bui-conversation-notice">{notice}</div>}<div className="bui-conversation-body"><div className="bui-conversation-column"><div className="bui-thread" ref={threadRef} onScroll={onThreadScroll} role="log" aria-label={threadLabel} aria-live="off" tabIndex={0}><div className="bui-thread-inner">{children}</div></div><div className="bui-composer-dock">{floatingActions && <div className="bui-composer-rail">{floatingActions}</div>}{composer}</div></div>{companion && <aside className="bui-companion">{companion}</aside>}</div></div>;
}
export interface ConversationJumpProps { label: string; count?: number; onClick: () => void }
export function ConversationJump({ label, count = 0, onClick }: ConversationJumpProps) {
  return <Tooltip title={label}><Button className="bui-latest-action" size="sm" aria-label={label} onClick={onClick} icon={<Glyph name="arrow" className="bui-rotate" size={16} />}>{count > 0 && <span className="bui-unread-count">{count > 99 ? "99+" : count}</span>}</Button></Tooltip>;
}
export interface DraftSuggestion { key: string; label: ReactNode; description?: ReactNode; onSelect: () => void }
export interface ConversationEmptyProps { title: ReactNode; description?: ReactNode }
export function ConversationEmpty({ title, description }: ConversationEmptyProps) { return <section className="bui-conversation-empty"><h2>{title}</h2>{description && <div >{description}</div>}</section>; }
export interface MessageEntryProps { kind: "user" | "agent" | "system"; author?: ReactNode; timestamp?: ReactNode; status?: ReactNode; actions?: ReactNode; children: ReactNode; attachments?: ReactNode; work?: ReactNode; label?: string }
export function MessageEntry({ kind, author, timestamp, status, actions, children, attachments, work, label }: MessageEntryProps) {
  return <article className={`bui-message bui-message--${kind}`} aria-label={label}>{(author || timestamp || status) && <header className="bui-message-meta">{author && <strong>{author}</strong>}{timestamp && <span>{timestamp}</span>}{status}</header>}{work && <div className="bui-message-work">{work}</div>}<div className="bui-message-body">{children}</div>{attachments && <div className="bui-message-attachments">{attachments}</div>}{actions && <footer className="bui-message-actions">{actions}</footer>}</article>;
}
export interface AttachmentSlotProps { name: ReactNode; meta?: ReactNode; preview?: ReactNode; actions?: ReactNode; status?: ReactNode }
export function AttachmentSlot({ name, meta, preview, actions, status }: AttachmentSlotProps) { return <div className="bui-attachment">{preview && <div className="bui-attachment-preview">{preview}</div>}<div className="bui-attachment-info"><Glyph name="file" size={16} /><div className="bui-attachment-copy"><strong>{name}</strong>{meta && <span className="bui-muted">{meta}</span>}{status}</div>{actions && <div className="bui-actions">{actions}</div>}</div></div>; }
export interface ComposerFrameProps { input: ReactNode; attachments?: ReactNode; suggestions?: ReactNode; startActions?: ReactNode; submitAction: ReactNode; hint?: ReactNode; status?: ReactNode; recovery?: ReactNode; disabled?: boolean; label: string }
export function ComposerFrame({ input, attachments, suggestions, startActions, submitAction, hint, status, recovery, disabled = false, label }: ComposerFrameProps) {
  return <section className="bui-composer-area" aria-label={label} aria-disabled={disabled || undefined}>{recovery && <div className="bui-composer-recovery">{recovery}</div>}{suggestions && <div className="bui-composer-suggestions">{suggestions}</div>}<div className="bui-composer-frame">{attachments && <div className="bui-composer-attachments">{attachments}</div>}<div className="bui-composer-input-wrap">{input}</div><footer className="bui-composer-toolbar"><div className="bui-composer-start">{startActions}</div>{status && <div className="bui-composer-status" role="status">{status}</div>}<div className="bui-composer-submit">{submitAction}</div></footer></div>{hint && <div className="bui-composer-hint">{hint}</div>}</section>;
}
export interface WorkRecordProps { title: ReactNode; label?: string; status?: ReactNode; active: boolean; expanded?: boolean; onExpandedChange?: (expanded: boolean) => void; children: ReactNode }
export function WorkRecord({ title, label, status, active, expanded, onExpandedChange, children }: WorkRecordProps) {
  const [localExpanded, setLocalExpanded] = useState(false);
  const bodyId = useId();
  const open = active || (expanded ?? localExpanded);
  return <section className={`bui-work${active ? " bui-work--active" : ""}`} aria-label={label} aria-labelledby={label ? undefined : `${bodyId}-title`}><header className="bui-work-heading">{active ? <span className="bui-inline"><span className="bui-spinner" aria-hidden="true" /><strong id={`${bodyId}-title`}>{title}</strong></span> : <Button variant="quiet" size="xs" aria-expanded={open} aria-controls={bodyId} onClick={() => { if (expanded === undefined) setLocalExpanded(!open); onExpandedChange?.(!open); }} icon={<Glyph name="chevron" size={14} className={open ? "bui-rotate" : undefined} />}><span id={`${bodyId}-title`}>{title}</span></Button>}{status}</header><div id={bodyId} className="bui-work-body" hidden={!open}>{children}</div></section>;
}
export interface WorkStepProps { title: ReactNode; meta?: ReactNode; status?: ReactNode; children?: ReactNode; expanded?: boolean; onExpandedChange?: (expanded: boolean) => void }
export function WorkStep({ title, meta, status, children, expanded, onExpandedChange }: WorkStepProps) {
  const [localExpanded, setLocalExpanded] = useState(false);
  const bodyId = useId();
  const open = expanded ?? localExpanded;
  return <div className="bui-work-step"><header className="bui-work-step-heading">{children ? <Button variant="quiet" size="xs" aria-expanded={open} aria-controls={bodyId} onClick={() => { if (expanded === undefined) setLocalExpanded(!open); onExpandedChange?.(!open); }} icon={<Glyph name="chevron" size={12} className={open ? "bui-rotate" : undefined} />}>{title}</Button> : <strong>{title}</strong>}{status}{meta && <span className="bui-work-step-meta">{meta}</span>}</header>{children && <div className="bui-work-step-detail" hidden={!open} id={bodyId}>{children}</div>}</div>;
}
export interface ApprovalChoice { key: string; label: ReactNode; danger?: boolean; onChoose: () => void }
export interface ApprovalPanelProps { title: ReactNode; description?: ReactNode; detail?: ReactNode; choices: ApprovalChoice[]; busy?: boolean; status?: ReactNode }
export function ApprovalPanel({ title, description, detail, choices, busy = false, status }: ApprovalPanelProps) {
  const heading = useId();
  return <section className="bui-approval" aria-labelledby={heading} aria-busy={busy}><header><Glyph name="lock" size={16} /><h3 id={heading}>{title}</h3>{status}</header>{description && <div className="bui-muted">{description}</div>}{detail && <div className="bui-approval-detail">{detail}</div>}<footer className="bui-actions">{choices.map((choice) => <Button variant={choice.danger ? "danger" : "secondary"} key={choice.key} size="sm" disabled={busy} onClick={choice.onChoose}>{choice.label}</Button>)}</footer></section>;
}
export interface ContextUsageProps { label: string; usedLabel: string; limitLabel: string; used: number; max: number; percent: number; details?: ReactNode }
export function ContextUsage({ label, usedLabel, limitLabel, used, max, percent, details }: ContextUsageProps) {
  const bounded = Number.isFinite(percent) ? Math.max(0, Math.min(100, percent)) : 0;
  return <section className="bui-context"><header><strong>{label}</strong><span className="bui-mono">{bounded}%</span></header><div className="bui-context-meter" role="meter" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={bounded} aria-valuetext={`${usedLabel}: ${used}; ${limitLabel}: ${max}`}><span style={{ width: `${bounded}%` }} /></div><dl className="bui-context-values"><div><dt>{usedLabel}</dt><dd>{used}</dd></div><div><dt>{limitLabel}</dt><dd>{max}</dd></div></dl>{details && <div className="bui-context-details">{details}</div>}</section>;
}
export interface ComputerPanelProps { title: ReactNode; modeLabel: ReactNode; status?: ReactNode; elapsed?: ReactNode; actions?: ReactNode; children: ReactNode; footer?: ReactNode; expanded?: boolean }
export function ComputerPanel({ title, modeLabel, status, elapsed, actions, children, footer, expanded = false }: ComputerPanelProps) { return <section className={`bui-computer${expanded ? " bui-computer--expanded" : ""}`}><header className="bui-computer-header"><div className="bui-computer-heading"><h2>{title}</h2><div className="bui-computer-meta"><span>{modeLabel}</span>{status}{elapsed && <span className="bui-mono">{elapsed}</span>}</div></div>{actions && <div className="bui-actions">{actions}</div>}</header><div className="bui-computer-content">{children}</div>{footer && <footer className="bui-computer-footer">{footer}</footer>}</section>; }
export interface ComputerOutputProps { kind: "file" | "terminal" | "search"; title?: ReactNode; meta?: ReactNode; children: ReactNode; truncated?: ReactNode }
export function ComputerOutput({ kind, title, meta, children, truncated }: ComputerOutputProps) { return <div className={`bui-output bui-output--${kind}`}>{(title || meta) && <header className="bui-output-header">{title && <strong>{title}</strong>}{meta && <span className="bui-muted">{meta}</span>}</header>}<div className="bui-output-body" tabIndex={0}>{children}</div>{truncated && <div className="bui-output-truncated" role="status">{truncated}</div>}</div>; }
export function BrowserControlBar({ status, description, action, danger = false }: { status: ReactNode; description?: ReactNode; action?: ReactNode; danger?: boolean }) { return <div className={`bui-browser-control${danger ? " bui-tone-warning" : ""}`}><div><strong role="status">{status}</strong>{description && <div >{description}</div>}</div>{action}</div>; }
export function CapabilityHeader({ title, description, scope, actions }: { title: ReactNode; description?: ReactNode; scope?: ReactNode; actions?: ReactNode }) { return <header className="bui-capability-header"><div>{scope && <span className="bui-eyebrow">{scope}</span>}<h2>{title}</h2>{description && <div className="bui-muted">{description}</div>}</div>{actions && <div className="bui-actions">{actions}</div>}</header>; }
export function SearchToolbar({ search }: { search: ReactNode }) { return <div className="bui-search-toolbar">{search}</div>; }
export interface GuideSheetProps { title: ReactNode; intro: ReactNode; sections: { key: string; title: ReactNode; body: ReactNode }[]; examples?: DraftSuggestion[]; action?: ReactNode; notice?: ReactNode }
export function GuideSheet({ title, intro, sections, examples, action, notice }: GuideSheetProps) { return <div className="bui-guide"><header><h2>{title}</h2><div className="bui-muted">{intro}</div></header><ol className="bui-guide-sections">{sections.map((section) => <li key={section.key}><h3>{section.title}</h3><div>{section.body}</div></li>)}</ol>{examples && examples.length > 0 && <ul className="bui-guide-examples">{examples.map((example) => <li key={example.key}><Button variant="quiet" onClick={example.onSelect}><span><strong>{example.label}</strong>{example.description && <span className="bui-muted">{example.description}</span>}</span><Glyph name="arrow" size={16} /></Button></li>)}</ul>}{notice}{action && <footer className="bui-actions">{action}</footer>}</div>; }
