// Package handofftransform stages the one-time technical-namespace data
// transformation. It can atomically publish a transaction-owned data tree but
// cannot commit the namespace handoff; that durable protocol decision remains
// with the coordinator after all independent validators have succeeded.
package handofftransform

import (
	"context"
	"errors"
	"fmt"
	"os"
	"regexp"
	"time"

	"github.com/Noyv3x/enterprise-agent-platform/manager/internal/identity"
)

const (
	SchemaVersion       = 1
	ManifestSchema      = 1
	markerName          = ".handoff-staging.json"
	manifestName        = "handoff-manifest.json"
	inputDirectoryName  = ".handoff-inputs"
	defaultCopyBuffer   = 256 << 10
	maximumMetadataSize = 8 << 20
)

var (
	transactionIDPattern = regexp.MustCompile(`^handoff_[0-9a-f]{32}$`)
	resourceNamePattern  = regexp.MustCompile(`^[a-z][a-z0-9_-]{0,63}$`)
	sha256Pattern        = regexp.MustCompile(`^[0-9a-f]{64}$`)

	// ErrInjectedCrash is reserved for deterministic crash-boundary tests. A
	// fault hook returning it leaves the transaction-owned staging tree in
	// place, exactly as process death would. Ordinary errors are compensated.
	ErrInjectedCrash = errors.New("injected handoff transform crash")
)

// ResourceKind describes how one explicitly allow-listed resource is staged.
// No recursive discovery outside these declarations is performed.
type ResourceKind string

const (
	ByteExactFile ResourceKind = "byte_exact_file"
	ByteExactTree ResourceKind = "byte_exact_tree"
	SecretFile    ResourceKind = "secret_file"
	Structured    ResourceKind = "structured"
	Generated     ResourceKind = "generated"
)

// AccessClass declares which filesystem capability may touch a resource.
// Native resources are handled by the deployment UID. ContainerOwnedTree is
// deliberately narrower than an owner allow-list: only the injected
// PrivilegedTreeFS may inventory, copy, verify, or remove that tree.
type AccessClass string

const (
	NativeAccess       AccessClass = "native"
	ContainerOwnedTree AccessClass = "container_owned_tree"
)

// NodeType is the required type at the root of a resource.
type NodeType string

const (
	RegularFile NodeType = "file"
	Directory   NodeType = "directory"
)

// Owner is an exact source or target filesystem identity accepted for a
// resource. Empty owner lists default to the deployment UID/GID.
type Owner struct {
	UID uint32 `json:"uid"`
	GID uint32 `json:"gid"`
}

// Resource is one closed-world staging rule. Source and Target are canonical
// slash-separated paths relative to the bound data roots. Generated resources
// have no Source. Structured and Generated resources require both a
// Transformer and a Validator.
type Resource struct {
	Name            string
	Kind            ResourceKind
	Access          AccessClass
	PrivilegedImage string
	Source          string
	Target          string
	Type            NodeType
	Required        bool
	SourceOwners    []Owner
	TargetOwners    []Owner
	AdditionalBytes uint64
	Transformer     Transformer
	Validator       Validator
	// SourceExclude omits reviewed source-only state from the transaction input
	// and target. SourceValidator independently validates every omitted
	// authoritative entry before each source inventory.
	SourceExclude   func(string) bool
	SourceValidator SourceValidator
	// SourceInventoryValidator applies path-specific policy after the generic
	// no-link, same-device and owner-set inventory. It is used only when a
	// structured schema needs a narrower per-entry rule than its resource-wide
	// owner set, and its semantics must be bound by TransformationSHA256.
	SourceInventoryValidator SourceInventoryValidator
	SchemaIdentifier         string
	SchemaVersion            int
	// TransformationSHA256 binds semantic inputs not otherwise present in the
	// request identity (authoritative identity sets, image digests, deterministic
	// timestamps, and generated bytes). Structured and Generated resources must
	// always provide it.
	TransformationSHA256 string
}

// Request binds one immutable source tree to one transaction-owned target
// sibling staging tree. TargetRoot is the final path, which must not exist.
type Request struct {
	TransactionID string
	SourceRoot    string
	TargetRoot    string
	Resources     []Resource
	ReserveBytes  uint64
}

// TechnicalMapping is supplied to structured transformers. Values come only
// from compile-time identities, never from branding, environment, or a
// manifest-provided arbitrary profile.
type TechnicalMapping struct {
	Source identity.Profile
	Target identity.Profile
}

// TransformInput limits a transformer to its declared source and target. The
// source path is empty for Generated resources. Structured resources receive a
// transaction-local, read-only snapshot rather than the authoritative source
// path. Transformers must create exactly TargetPath without symlinks or
// hardlinks.
type TransformInput struct {
	TransactionID string
	SourcePath    string
	TargetPath    string
	Mapping       TechnicalMapping
	// SourceEntries is the immutable preflight inventory of the authoritative
	// source. Structured inputs themselves are made read-only before a
	// transformer receives them, so original mode/mtime/owner invariants must be
	// taken from this manifest rather than inferred from the temporary copy.
	SourceEntries []Entry
}

// ValidationInput exposes immutable manifests instead of letting a validator
// silently redefine what the engine copied.
type ValidationInput struct {
	TransactionID string
	Resource      Resource
	SourcePath    string
	TargetPath    string
	Mapping       TechnicalMapping
	SourceEntries []Entry
	TargetEntries []Entry
}

type Transformer interface {
	Transform(context.Context, TransformInput) error
}

type Validator interface {
	Validate(context.Context, ValidationInput) error
}

type SourceValidator interface {
	ValidateSource(context.Context, string) error
}

type SourceInventoryValidator interface {
	ValidateSourceInventory([]Entry) error
}

type TransformFunc func(context.Context, TransformInput) error

func (f TransformFunc) Transform(ctx context.Context, input TransformInput) error {
	return f(ctx, input)
}

type ValidateFunc func(context.Context, ValidationInput) error

func (f ValidateFunc) Validate(ctx context.Context, input ValidationInput) error {
	return f(ctx, input)
}

// Entry is the content-addressed evidence for one resource node. Path is
// relative to the resource root; "." denotes the root itself.
type Entry struct {
	Resource      string   `json:"resource"`
	Path          string   `json:"path"`
	Type          NodeType `json:"type"`
	Mode          uint32   `json:"mode"`
	UID           uint32   `json:"uid"`
	GID           uint32   `json:"gid"`
	LinkCount     uint64   `json:"link_count"`
	Size          int64    `json:"size"`
	AllocatedSize uint64   `json:"allocated_size"`
	ModifiedNanos int64    `json:"modified_nanos"`
	SHA256        string   `json:"sha256,omitempty"`
}

type ResourceManifest struct {
	Name             string       `json:"name"`
	Kind             ResourceKind `json:"kind"`
	Access           AccessClass  `json:"access"`
	PrivilegedImage  string       `json:"privileged_image,omitempty"`
	Source           string       `json:"source,omitempty"`
	Target           string       `json:"target"`
	SchemaIdentifier string       `json:"schema_identifier,omitempty"`
	SchemaVersion    int          `json:"schema_version,omitempty"`
	SourceEntries    []Entry      `json:"source_entries,omitempty"`
	TargetEntries    []Entry      `json:"target_entries"`
	Validation       string       `json:"validation"`
}

type Manifest struct {
	SchemaVersion int                `json:"schema_version"`
	TransactionID string             `json:"transaction_id"`
	SourceRoot    string             `json:"source_root"`
	TargetRoot    string             `json:"target_root"`
	SourceProfile string             `json:"source_profile"`
	TargetProfile string             `json:"target_profile"`
	RequiredBytes uint64             `json:"required_bytes"`
	Resources     []ResourceManifest `json:"resources"`
	CreatedAt     time.Time          `json:"created_at"`
}

type Result struct {
	StagingRoot    string
	ManifestPath   string
	ManifestSHA256 string
	RequiredBytes  uint64
	Manifest       Manifest
}

// Point names stable interruption boundaries used by the crash replay tests.
type Point struct {
	Name     string
	Resource string
}

type Engine struct {
	UID        int
	GID        int
	Now        func() time.Time
	CopyBuffer int
	Fault      func(Point) error
	// PrivilegedTreeFS is mandatory when any resource declares
	// ContainerOwnedTree. It is injected by the helper production assembly and
	// is never inferred from an owner UID/GID.
	PrivilegedTreeFS PrivilegedTreeFS
}

type PrivilegedOperation string

const (
	PrivilegedInventory PrivilegedOperation = "inventory"
	PrivilegedCopy      PrivilegedOperation = "copy"
	PrivilegedRemove    PrivilegedOperation = "remove"
)

type PrivilegedRemovalKind string

const (
	RemovalStagingMarker     PrivilegedRemovalKind = "staging_marker"
	RemovalFencedPublication PrivilegedRemovalKind = "fenced_publication"
)

// PrivilegedRemovalProof binds deletion to durable transaction evidence. A
// kind string alone is never sufficient: staging requires its exact marker;
// published rollback additionally requires the durable manifest and the
// independent target-writer fence binding.
type PrivilegedRemovalProof struct {
	Kind               PrivilegedRemovalKind `json:"kind"`
	MarkerSHA256       string                `json:"marker_sha256"`
	ManifestSHA256     string                `json:"manifest_sha256,omitempty"`
	FenceBindingSHA256 string                `json:"fence_binding_sha256,omitempty"`
}

// PrivilegedTreeRequest is the closed capability passed from Engine to the
// privileged implementation. Host paths are never accepted from release JSON
// or user input; Engine derives them from its already validated Request.
type PrivilegedTreeRequest struct {
	SchemaVersion  int
	Operation      PrivilegedOperation
	TransactionID  string
	RequestSHA256  string
	ResourceName   string
	ImageDigest    string
	SourcePath     string
	TargetRoot     string
	TargetRelative string
	SourceOwners   []Owner
	TargetOwners   []Owner
	ExpectedSource []Entry
	ExpectedTarget []Entry
	RemovalProof   PrivilegedRemovalProof
}

type PrivilegedTreeResult struct {
	Entries       []Entry
	SourceEntries []Entry
	TargetEntries []Entry
	Removed       bool
}

// PrivilegedTreeFS has no generic path or command operation. Its methods are
// deliberately package-private: other Manager packages may construct the
// production implementation and inject it into Engine, but cannot invoke the
// privileged deletion capability directly and bypass ProductionBoundary's
// opaque target-writer fence proof. Each method is bound to one explicit
// ByteExactTree resource and must return independently verified inventory
// evidence.
type PrivilegedTreeFS interface {
	inventory(context.Context, PrivilegedTreeRequest) (PrivilegedTreeResult, error)
	copy(context.Context, PrivilegedTreeRequest) (PrivilegedTreeResult, error)
	remove(context.Context, PrivilegedTreeRequest) (PrivilegedTreeResult, error)
}

// UnsupportedSchemaError is returned instead of guessing how to rewrite a
// machine-owned data format that lacks a complete versioned contract.
type UnsupportedSchemaError struct {
	Resource string
	Schema   string
	Reason   string
}

func (e *UnsupportedSchemaError) Error() string {
	return fmt.Sprintf("handoff transform for %s schema %s is unavailable: %s", e.Resource, e.Schema, e.Reason)
}

func (e Engine) effectiveUID() int {
	if e.UID < 0 {
		return os.Getuid()
	}
	if e.UID == 0 && os.Getuid() != 0 {
		// The zero-value Engine should mean the invoking deployment identity,
		// not root, when tests or production run unprivileged.
		return os.Getuid()
	}
	return e.UID
}

func (e Engine) effectiveGID() int {
	if e.GID < 0 {
		return os.Getgid()
	}
	if e.GID == 0 && os.Getgid() != 0 {
		return os.Getgid()
	}
	return e.GID
}
