# Generated from docs/contracts/runtime-policy.json by scripts/docs_sync.py; do not edit.
from __future__ import annotations

RUNTIME_POLICY_SCHEMA_VERSION = 1

RUN_IDLE_TIMEOUT_DEFAULT_SECONDS = 1800
RUN_IDLE_TIMEOUT_MINIMUM_SECONDS = 0
RUN_IDLE_TIMEOUT_MAXIMUM_SECONDS = 86400
RUN_IDLE_TIMEOUT_PLATFORM_ENVIRONMENT_VARIABLE = 'ENTERPRISE_AGENT_RUNTIME_IDLE_TIMEOUT_SECONDS'
RUN_IDLE_TIMEOUT_RUNTIME_ENVIRONMENT_VARIABLE = 'AGENT_RUNTIME_RUN_IDLE_TIMEOUT_MS'

MAX_TURNS_PER_RUN_DEFAULT = 90
MAX_TURNS_PER_RUN_MINIMUM = 1
MAX_TURNS_PER_RUN_MAXIMUM = 1000
MAX_TURNS_PER_RUN_RUNTIME_ENVIRONMENT_VARIABLE = 'AGENT_RUNTIME_MAX_TURNS'

TERMINAL_TIMEOUT_DEFAULT_MILLISECONDS = 180000
TERMINAL_TIMEOUT_MINIMUM_MILLISECONDS = 100
TERMINAL_TIMEOUT_MAXIMUM_MILLISECONDS = 3600000
TERMINAL_TIMEOUT_RUNTIME_ENVIRONMENT_VARIABLE = 'AGENT_RUNTIME_TERMINAL_TIMEOUT_MS'
