//go:build linux

// Package handoffstartup routes a Manager process to an immutable technical
// profile before the application is constructed.
//
// A process started while the persistent handoff helper owns the Store uses a
// one-shot SOCK_SEQPACKET capability. A process started after a terminal
// handoff observes journals through Store.OpenObservation's retained dirfd and
// global lease. Neither path accepts a profile name from argv or environment.
package handoffstartup

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/Noyv3x/enterprise-agent-platform/manager/internal/handoff"
	"github.com/Noyv3x/enterprise-agent-platform/manager/internal/identity"
)

const (
	SchemaVersion  = 1
	SocketBasename = "startup-capability.sock"
	// AbortSourceSocketBasename is a distinct, source-only capability. It is
	// never interpreted as a formal source/target StartupSnapshot channel.
	AbortSourceSocketBasename = "abort-source-capability.sock"
	DefaultTTL                = 15 * time.Second
	MaximumTTL                = 30 * time.Second
	maxPacketBytes            = 16 << 10
)

var (
	ErrCapabilityRequired = errors.New("a helper startup capability is required for the active handoff")
	ErrCapabilityConsumed = errors.New("the startup capability has already been consumed")
	ErrUnsafePath         = errors.New("unsafe startup capability path")
	ErrProfileConflict    = errors.New("handoff journals do not select one technical profile")
)

// RuntimePaths are the absolute identities resolved before normal Manager
// configuration is opened. Callers always provide both source and target; a
// single caller-selected profile is intentionally not part of this API.
type RuntimePaths struct {
	StableBinary string
	ConfigPath   string
	DataRoot     string
	StateRoot    string
	SocketPath   string
}

// Bindings contains both immutable technical layouts. Static namespace,
// Compose and network values come from identity.Profile rather than callers.
type Bindings struct {
	Source RuntimePaths
	Target RuntimePaths
}

// StartupSnapshot is the closed-world, read-only handoff view issued to one
// process. It contains no token or secret and is useful only with the nonce
// generated by that process over the authenticated channel.
type StartupSnapshot struct {
	SchemaVersion  int                    `json:"schema_version"`
	TransactionID  string                 `json:"transaction_id"`
	Revision       uint64                 `json:"revision"`
	BindingSHA256  string                 `json:"binding_sha256"`
	Nonce          string                 `json:"nonce"`
	ProfileID      string                 `json:"profile_id"`
	Status         handoff.Status         `json:"status"`
	Phase          handoff.Phase          `json:"phase"`
	DesiredOutcome handoff.DesiredOutcome `json:"desired_outcome"`
	Generation     string                 `json:"generation"`
	ManagerSHA256  string                 `json:"manager_sha256"`
	StableBinary   string                 `json:"stable_binary"`
	ConfigPath     string                 `json:"config_path"`
	ConfigSHA256   string                 `json:"config_sha256"`
	DataRoot       string                 `json:"data_root"`
	StateRoot      string                 `json:"state_root"`
	SocketPath     string                 `json:"socket_path"`
	ComposeProject string                 `json:"compose_project"`
	CoreNetwork    string                 `json:"core_network"`
	IssuedAt       time.Time              `json:"issued_at"`
	ExpiresAt      time.Time              `json:"expires_at"`
}

// Decision is returned before ordinary Manager state is opened. Snapshot is
// present only for helper-mediated startup; terminal routing exposes only the
// minimal journal identity needed for audit.
type Decision struct {
	ActiveProfile identity.ActiveProfile
	Profile       identity.Profile
	// Paths is the exact runtime binding selected by the helper capability or
	// terminal journal.  It is an output of routing, never an argv input used to
	// select a profile.
	Paths         RuntimePaths
	TransactionID string
	Revision      uint64
	BindingSHA256 string
	ConfigSHA256  string
	Snapshot      *StartupSnapshot
}

// Clock is injectable for deterministic expiry tests. Production callers
// should omit it.
type Clock func() time.Time

// IssuerOptions are supplied by the persistent helper while it owns the
// writer lease. TransactionDirectory must be the already verified directory
// for Lease's journal.
type IssuerOptions struct {
	Lease                JournalLease
	TransactionDirectory string
	Bindings             Bindings
	TTL                  time.Duration
	Clock                Clock
}

// JournalLease is deliberately read-only. Production passes the opaque
// handoff.StartupLease derived from the coordinator's held writer lease;
// tests may supply the Helper itself because it implements this narrow view.
type JournalLease interface {
	Load() (handoff.Journal, error)
}

// Router owns startup selection. The Store is already open and retains its
// verified root descriptor; terminal routing never reopens Store.Root by path.
type Router struct {
	store    *handoff.Store
	bindings Bindings
	clock    Clock
	pid      func() int
}

// NewRouter constructs a router that always knows both technical layouts.
func NewRouter(store *handoff.Store, bindings Bindings) (*Router, error) {
	return newRouter(store, bindings, time.Now, currentPID)
}

// NewHelperRouter constructs the lock-internal route used by a freshly
// started handoff participant. It deliberately accepts no Store, so this path
// cannot deadlock by trying to reacquire the helper's writer lease.
func NewHelperRouter(bindings Bindings) (*Router, error) {
	return newHelperRouter(bindings, time.Now, currentPID)
}

// NewCapabilityRouter constructs the participant-side Router.  The helper's
// authenticated one-shot snapshot is the binding authority, so this consumer
// deliberately accepts no caller-supplied source or target paths.
func NewCapabilityRouter() *Router {
	return &Router{clock: time.Now, pid: currentPID}
}

// NewTerminalRouter constructs the post-handoff Router.  Runtime bindings are
// derived from the closed journals while the Store observation lease is held;
// argv and environment paths cannot populate them.
func NewTerminalRouter(store *handoff.Store) (*Router, error) {
	if store == nil {
		return nil, errors.New("startup router requires an open handoff Store")
	}
	return &Router{store: store, clock: time.Now, pid: currentPID}, nil
}

// RouteTerminal selects source for an untouched/rolled-back deployment and
// target only for one fully verified committed handoff.
func (r *Router) RouteTerminal(ctx context.Context) (Decision, error) {
	return r.routeTerminal(ctx, true)
}

// RouteTerminalAuthorityRetained performs the same authority-only route while
// returning the exact global observation that selected it. The caller must
// retain this lease through its owner-specific plan/recovery proof, revalidate
// it immediately before authority transfer, and Close it on every exit.
func (r *Router) RouteTerminalAuthorityRetained(ctx context.Context) (Decision, *AuthorityLease, error) {
	return r.routeAuthorityRetained(ctx, nil)
}

// RouteBaselineSourceAuthorityRetained initializes/opens the neutral Store
// for a no-journal source deployment and returns an empty retained authority
// observation. If a journal appeared before the lease was acquired, the
// terminal journal remains authoritative and the supplied baseline is not
// used.
func (r *Router) RouteBaselineSourceAuthorityRetained(ctx context.Context, paths RuntimePaths) (Decision, *AuthorityLease, error) {
	return r.routeAuthorityRetained(ctx, &paths)
}

// RouteBaselineSource is the only no-journal route. It accepts the source
// profile only after proving that this process executes the configured source
// stable inode and that the complete source runtime layout is present. A
// target binary therefore cannot turn an absent journal into a profile hint.
func RouteBaselineSource(bindings Bindings) (Decision, error) {
	return routeBaselineSource(bindings, true)
}

// RouteBaselineSourcePaths is the no-journal source route for an installer-
// selected absolute config path.  A target binding is intentionally absent:
// without a journal there is no authority to construct target identity.
func RouteBaselineSourcePaths(paths RuntimePaths) (Decision, error) {
	return routeBaselineSourcePaths(paths, true)
}

func routeBaselineSource(bindings Bindings, requireStableProcess bool) (Decision, error) {
	if err := validateBindings(bindings); err != nil {
		return Decision{}, err
	}
	return routeBaselineSourcePaths(bindings.Source, requireStableProcess)
}

func routeBaselineSourcePaths(paths RuntimePaths, requireStableProcess bool) (Decision, error) {
	if err := validateRuntimePaths("source", identity.SourceProfile(), paths); err != nil {
		return Decision{}, err
	}
	if requireStableProcess {
		if err := verifyProcessExecutable(currentPID(), paths.StableBinary, ""); err != nil {
			return Decision{}, fmt.Errorf("verify baseline source Manager executable: %w", err)
		}
	}
	if err := verifyRuntimeLayout(paths); err != nil {
		return Decision{}, fmt.Errorf("verify baseline source Manager layout: %w", err)
	}
	return Decision{ActiveProfile: identity.SourceActiveProfile(), Profile: identity.SourceProfile(), Paths: paths}, nil
}
